- src/entities/user.entity.ts
- src/jobpost/jobpostProgrammersScraper.ts
User Entity 의 다대다 userstack Join Table 명 소문자로 수정
1. user.entitiy.ts 파일의 @ManyToMany 관계 @JoinTable 설정에서의 userStack -> userstack 
2. 프로그래머스 채용공고 크롤링 파일 작업중
> Fix: User Entity 의 다대다 userstack Join Table 명 소문자로 수정

- src/jobpost/scraper/jobpostProgrammersScraper.ts
프로그래머스 채용공고 연봉데이터 양식 수정
jobpostProgrammersScraper.ts 의 salary 수정
> refactor: 프로그래머스 연봉 데이터 양식변경

- src/jobpost/scraper/jobpostSaraminAxiosScraper.ts
- src/jobpost/scraper/jobpostSaraminSeleniumScraper.ts
사람인 회사이름, 연봉 정보 변경
jobpostSaraminSeleniumScraper.ts 의 salary 수치에 *10000
jobpostSaraminAxiosScraper.ts의 회사 이름에 (주) 빼기
> refactor: 사람인 회사 이름, 연봉 정보 변경

- src/jobpost/jobpost.controller.ts
- src/jobpost/jobpost.repository.ts
- src/jobpost/jobpost.service.ts
- src/public/css/common.css
- src/views/jobposts.ejs
- src/views/main.ejs
기존에 썼던 order 키를 sort 와 order 키 2개로 나눴습니다.
기존 예시: /jobposts?order=recent-desc
수정 예시: /jobposts?sort=recent&order=desc
> chore/Filter query parameter 키 값 수정

- src/views/main.ejs
- 로그인 한 유저가 좋아요한 공고는 노란색으로 표시됨
> feat: 로그인 한 유저 기준 좋아요 한 공고 표시

- src/jobpost/jobpost.controller.ts
- src/jobpost/jobpost.repository.ts
- src/jobpost/jobpost.service.ts
- src/public/css/common.css
- src/public/css/jobposts.css
- src/public/css/main.css
- src/views/header.ejs
- src/views/jobposts.ejs
- src/views/main.ejs
1. 키워드 별로 공고 불러오기 구현 완료
2. 검색 기능 구현 완료
3. CSS와 인기순으로 불러오기 수정
4. 전체 공고 페이지에서 pagination 적용
5. 전체 공고 페이지에서 찜된 공고에 별 표시와 찜 된 공고에 별 CSS 수정
필터 목록이 생각보다 길어서 필터 목록에서 버튼이 많아질 경우 목록 보이기 숨기기 버튼을 추가하거나, 모달 창으로 옮기거나, dropdown 박스로 수정하는 것 중에 수정을 고려하면 좋겠습니다.
> Feature/키워드 별로 공고 불러오기와 검색 기능

- src/jobpost/jobpost.repository.ts
> fix: add column

- src/public/css/footer.css
- src/public/css/jobposts.css
- src/views/footer.ejs
- src/views/index.ejs
- src/views/jobposts.ejs
- 키워드 검색 display fixed로 변경
- 페이지 목록 중간 정렬
- footer추가
> Feature: footer추가 및 페이지네이션 수정

- src/app.controller.ts
- src/cache/cache.service.ts
- src/jobpost/jobpost.repository.ts
- src/jobpost/jobpost.service.ts
- src/public/css/jobposts.css
- src/views/common.ejs
- src/views/jobposts.ejs
- src/views/main.ejs
> 좋아요 개선
- hash데이터가 아닌 sets로 구현
- 'jobpostId, userId' 를 넣고 srem으로 값이 있으면 바로 삭제하고 없으면 삭제x
- db에 넣지 않고 redis만 넣게됨 
- 불러올때 redis의 데이터를 불러와 비교 후 좋아요 처리
> 키워드 검색칸 fixed 제거
이후 cron으로 일정 시간마다 redis와 db의 데이터를 비교 후 동기화하면 될것 같음.
> Feature: 좋아요 redis 개선 및 불러오기 추가

- src/app.controller.ts
- src/cache/cache.service.ts
- 비회원이 조회 할 경우 동일하게 조회수가 올라가도록 변경
> Fix: 비회원 조회 구현

- src/views/jobposts.ejs
- src/views/modal.ejs
전에 `modalClose` 함수에서 쓰인 'refresh' 변수 삭제.
`modalOpen` 함수를 부를 때 url를 보내주면 모달이 닫히고 그 url로 redirect. url를 안 보내주면 모달 창만 닫힘.
> chore: 모달 함수 수정

- src/jobpost/jobpost.service.ts
- src/public/css/about.css
- src/public/css/common.css
- src/public/css/footer.css
- src/public/css/header.css
- src/public/css/main.css
- src/public/css/mypage.css
- src/views/about.ejs
- src/views/common.ejs
- src/views/detail.ejs
- src/views/footer.ejs
- src/views/header.ejs
- src/views/main.ejs
- src/views/myinfo.ejs
- src/views/mylikes.ejs
* ABOUT 페이지 디자인
* Warning 아이콘 및 메시지 디자인 수정
> Design: ABOUT 페이지 디자인 및 프론트 수정

- package.json
- procfile
> Feature: CI/CD 관련 코드

- src/_config/cache.config.ts
- src/public/css/common.css
- src/views/jobposts.ejs
- src/views/main.ejs
* 채용공고 로딩 시 Spinner 적용
* 메인화면 추천(로그인 시), 인기, 최신, 마감 채용공고  로딩 시 적용
* 전체보기 페이지 로딩 시 적용
> Refactor: 채용공고 로딩 시 Spinner 적용

- src/public/css/detail.css
* 채용공고 상세페이지 줄 간격 수정
* line-height 수정
> Refactor: 채용공고 상세페이지 내용 줄 간격 수정

- src/jobpost/jobpost.repository.ts
* orUpdate() 메서드 사용 시, 중복 된 데이터의 컬럼이 변경 점이 없을 때 그 row를 업데이트 시키지 않아
채용공고를 불러 올 때 updated_dtm 조건에 영향을 미침
* 채용공고 크롤링 시점에 중복된 데이터에 대한 update 로직을 변경
> Refactor: 채용공고 크롤링 DB 저장 시, orUpdate 로직 변경

- src/jobpost/jobpost.service.ts
* 메인페이지 최신공고, 곧 마감 공고 캐싱 적용 함수 수정
* Jobpost Service - 캐싱 적용 위치 수정
> Fix: 메인페이지 최신공고, 곧 마감 공고 캐싱 적용 함수 수정

- src/views/common.ejs
* 채용공고 카드 이미지 클릭 시 상세페이지 이동
* 이미지 태그를 a 태그로 감싸서 이동 가능하게 수정
> Refactor: 채용공고 카드 이미지 클릭 시 상세페이지 이동

- src/public/css/common.css
- src/views/common.ejs
* 채용공고 카드 이미지 위치 수정
* 이미지를 감싸는 a 태그에 class 를 설정하고, 중앙정렬 속성을 부여
> Refactor: 채용공고 카드 이미지 위치 수정

- src/_config/cache.config.ts
- src/public/css/common.css
- src/public/css/header.css
- src/public/css/main.css
- src/public/css/modal.css
- src/views/common.ejs
- src/views/header.ejs
- src/views/modal.ejs
- 메인페이지 carousel에 min-height 적용과 spinner를 중간으로 배치
- 메인페이지에 carousel 버튼 spacing 수정
- 공고 카드에 overflow 되는 제목과 회사 이름 ellipsis처리
- 기술 스택 이미지에 padding-bottom 적용
- 검색 바에 문구가 없으면 문구를 입력하라는 modal 열리게 수정
- modal css 수정
- 헤더에 검색 버튼 hover 시 background 삭제
- 헤더 로고에 padding 추가
> Refactor: 메인페이지, 헤더, 공고카드 CSS 수정

- src/views/jobposts.ejs
전체 공고 페이지에서 첫번째 주소가 전체일 때 두번째 주소 dropdown 버튼 안 보이게 수정
> Refactor: 첫번째 주소가 전체일 때 두번째 주소 dropdown 버튼 안 보이게 수정

- src/_config/cache.config.ts
- src/public/css/common.css
- src/public/css/footer.css
- src/public/css/header.css
- src/public/css/main.css
- src/public/css/modal.css
- src/views/common.ejs
- src/views/footer.ejs
- src/views/header.ejs
- src/views/jobposts.ejs
- src/views/modal.ejs
* 메인페이지 채용공고 carousel 디자인 수정
* Header 디자인 수정
* Footer 디자인 수정
> Refactor: 디자인 수정

- src/jobpost/jobpost.controller.ts
* 채용공고 크롤링 관련 함수 주석처리
* 서비스 배포 서버에서는 크롤링을 할 수 없음
> Refactor: 채용공고 크롤링 관련 함수 주석처리

- src/_config/cache.config.ts
- src/jobpost/jobpost.controller.ts
- src/jobpost/jobpost.service.ts
- src/jobpost/scraper/jobpostProgrammersScraper.ts
- src/jobpost/scraper/jobpostWantedAxiosScraper.ts
- Redis config 수정
- cron job UTC 시간으로 수정
- 원티드와 프로그래머스 스크레이퍼를 동기적으로 작동하게 수정
- 원티드와 프로그래머스 스크레이퍼 함수에 한 페이지를 스크레이프 후 DB에 저장하게 수정
> refactor: 원티드와 프로그래머스 스크레이퍼를 동기적으로 작동하게 수정
